trainer:
  max_steps: 2
  max_epochs: -1
  accelerator: gpu
  devices: 1
  precision: 16-mixed
  log_every_n_steps: 1
  limit_train_batches: 2
  limit_val_batches: 2
  limit_test_batches: 2
  val_check_interval: 2
  check_val_every_n_epoch: null
  enable_checkpointing: false

module:
  name: contrastive
  model_name: dinov2_boq
  learning_rate: 1.0e-4
  weight_decay: 1.0e-4
  val_recall_ks: [1, 5, 10]

datamodule:
  name: place_recognition
  train_dataset_name: sf_xl_small_cosplace
  val_dataset_names:
    - sf_xl_small_val
  test_dataset_names:
    - sf_xl_small_test
  batch_size: 4
  images_per_place: 2
  num_workers: 0
  transform:
    name: train
    image_size: 224
  val_transform:
    name: eval
    image_size: 224
  test_transform:
    name: eval
    image_size: 224
