wandb:
  project: placeforge
  name: sf_xl_small_intra_inter

trainer:
  max_epochs: 250
  accelerator: gpu
  devices: 1
  precision: 16-mixed
  log_every_n_steps: 10
  check_val_every_n_epoch: 2  # run validation every N epochs

module:
  name: contrastive
  model_name: resnet50_gem
  model_kwargs:
    descriptor_dim: 512
  learning_rate: 1.0e-4
  weight_decay: 1.0e-4
  val_recall_ks: [1, 5, 10]

datamodule:
  name: place_recognition
  train_dataset_name: sf_xl_small_intra_inter
  val_dataset_names:
    - pitts30k
  batch_size: 32
  images_per_place: 4
  num_workers: 2
  transform:
    name: train
    image_size: 224
  val_transform:
    name: eval
    image_size: 224
